
const COLLECTION_TASK_COMMENTS = "Task_comments"
const COLLECTION_MESSAGES = "Messages"
const COLLECTION_USERS = "Users"
const KEY_USER_ID = "user_id"

module.exports = { COLLECTION_TASK_COMMENTS, COLLECTION_MESSAGES, COLLECTION_USERS, KEY_USER_ID }